name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: OWASP Dependency Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "devops-node-app"
          path: "."
          format: "HTML"

      - name: Build Docker Image
        run: docker build -t devops-node-app:latest .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devops-node-app:latest'

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: docker tag devops-node-app:latest ${{ secrets.DOCKER_USERNAME }}/devops-node-app:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-node-app:latest
